server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://dbbirzumda.czwava9c8bpv.us-east-2.rds.amazonaws.com:5432/dbbirzumda
    username: postgres
    password: birzumda
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
app:
  pdf-file:
    root: src/main/resources/pdf/